name: Devops CI Pipeline

#When does this run?
on:
    push:
        branches: [ main ]
        paths:
            - 'devops-project-3.1/**'  #only run when this folder changes
    pull_request:
        branches: [ main ]
        paths:
            - 'devops-project-3.1/**'

#what does it do?
jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest

        steps:
            #step 1: Get the code
            - name: Chekout code
              uses: actions/checkout@v3

            #step 2: Setup Python
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            #step 3: Install dependencies
            - name: Install dependencies
              run: |
               cd devops-project-3.1
               pip install flask psycopg2-binary

            #step 4: Run tests
            - name: Run Tests
              run: |
               cd devops-project-3.1
               echo "Test passed"
               python -c "from app.app import app; print('App imports OK')"

            #step 5: Print success
            - name: Done
              run: echo "All test passed -ready to build"

            
